name: E2E Headless Tests

on:
  push:
    branches: ['**']     # tüm branch'lerde çalıştır
  pull_request:
  workflow_dispatch:

concurrency:
  group: e2e-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      TZ: Europe/Istanbul
      HEADLESS: "1"
      # BASE_URL'i burada açıkça tanımlıyoruz
      BASE_URL: "https://operator-frontend-v2-641161620205.europe-west1.run.app/"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install selenium
          fi

      # Kodun ENV'den okuyorsa zaten yeterli; .env gerekiyorsa da aşağıdaki adım işi çözer
      - name: Create .env from env (for scripts that require it)
        run: |
          {
            echo "BASE_URL=${BASE_URL}";
            echo "HEADLESS=${HEADLESS}";
          } > .env
          # değerleri göstermeden kısa sağlık kontrolü:
          awk -F= '{print $1"=[REDACTED]"}' .env

      - name: Run all tests (headless)
        run: python main.py

      - name: Upload artifacts (logs/screenshots if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
